package com.falchus.lib.minecraft.spigot.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Sound {
	LEVEL_UP("ENTITY_PLAYER_LEVELUP"),
	VILLAGER_NO("ENTITY_VILLAGER_NO"),
	NOTE_PLING("BLOCK_NOTE_BLOCK_PLING"),
	NOTE_BASS("BLOCK_NOTE_BLOCK_BASS"),
	NOTE_BASS_DRUM("BLOCK_NOTE_BLOCK_BASEDRUM"),
	AMBIENCE_THUNDER("ENTITY_LIGHTNING_BOLT_THUNDER"),
	CHEST_OPEN("BLOCK_CHEST_OPEN"),
	CHEST_CLOSE("BLOCK_CHEST_CLOSE"),
	CHICKEN_EGG_POP("ENTITY_CHICKEN_EGG"),
	ENDERDRAGON_GROWL("ENTITY_ENDER_DRAGON_GROWL"),
	BURP("ENTITY_PLAYER_BURP"),
	FIREWORK_LARGE_BLAST2("ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR"),
	ANVIL_LAND("BLOCK_ANVIL_LAND"),
	BAT_TAKEOFF("ENTITY_BAT_TAKEOFF");
	
	private final String modernName;
}
