name: FalchusLib
version: ${project.version}
api-version: 1.13
description: A library designed to simplify & speed up software development.
main: com.falchus.lib.minecraft.spigot.FalchusLibMinecraftSpigot
author: Falchus
authors: [Kalibrier]
website: lib-java.falchus.com

load: startup
softdepend: [LuckPerms]